Repository idearium/idearium-lib, pull requests merged in 2021-05, with the labels that each got.

#84 @idearium/log updates and first version of @idearium/log-insightops.
  .github/workflows/log-insightops.yml
  .vscode/settings.json
  .yarnrc
  docusaurus/docs/log-insightops.md
  docusaurus/docs/log.md
  docusaurus/sidebars.js
  packages/log-insightops/CHANGELOG.md
  packages/log-insightops/README.md
  packages/log-insightops/bin/insightops.js
  packages/log-insightops/package.json
  packages/log-insightops/tests/index.test.js
  packages/log/CHANGELOG.md
  packages/log/index.js
  packages/log/package.json
  packages/log/tests/index.test.js
  packages/mongoose/CHANGELOG.md
  packages/mongoose/package.json
  yarn.lock
Labels: review:allan, status:beta

#98 Doc typos
  docusaurus/docs/about.md
  docusaurus/docusaurus.config.js
Labels: review:scott

#105 Fetch fix
  packages/fetch/CHANGELOG.md
  packages/fetch/index.js
  packages/fetch/package.json
  packages/fetch/tests/index.test.js
Labels: review:scott, type:bug
